#!/bin/bash

# main script

DEST=`date +%Y%m%d%H`
PWD=`pwd`

# check for URL as arguement

if [ $# -eq 0 ]
then 
    echo "Please specify a 4chan thread URL"
    exit 1
fi

# make the pic directory

mkdir $PWD/$DEST

# get the URL

wget -O $PWD/$DEST/temp-html $1

# create the text file full of image URLs
# file first, then directory

./images-file $PWD/$DEST/temp-html $PWD/$DEST/temp-url 

# wget the image URLs

old_IFS=$IFS
IFS=$'\n'
for line in $(cat $PWD/$DEST/temp-url)
do
    wget -P $PWD/$DEST $line
done
IFS=$old_IFS

# cleanup
# rm $PWD/DEST/temp-html
# rm $PWD/DEST/temp-url
